apiVersion: v1
kind: Service
metadata:
  name: base
  labels:
    app: base
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: base
---
apiVersion: v1
kind: Service
metadata:
  name: base-preview
  labels:
    app: base
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: base