apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi
spec:
  project: default
  
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: deployment/overlays/local
    
    syncPolicy:
      automated: 
        prune: true
        selfHeal: true