apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: local

namePrefix: local-

resources:
  - ../../base

configMapGenerator:
  - name: base
    behavior: merge
    envs:
      - python-fastapi-service/application.yml